### ISSUE TITLE
About Placement Centered-Right

### ISSUE THREAD

**Issue by ulassenol** [mimo84/bootstrap-maxlength#105]
Hi, centered-right's position is not true. This is inside...

The original
![2015-08-22 22-57-09 dudukodu running - microsoft visual studio](https://cloud.githubusercontent.com/assets/9106568/9425668/50182a4e-4921-11e5-87f2-44416f57f8e7.png)

This is true
![2015-08-22 22-58-05 dudukodu running - microsoft visual studio](https://cloud.githubusercontent.com/assets/9106568/9425667/4fc71a3c-4921-11e5-8522-66c76af820b3.png)

By the way, thanks... :) this project helpful to me

**Comment by mimo84** [comment]
Thank you for this, however the idea of this placement is to mimic the position of the badge similar to what happens in the search widget in Google Chrome.
Do you think the name is a bit misleading? This is also the reason why there is not a `centered-left` option.

**Comment by djibe** [comment]
Please close issue.
