### ISSUE TITLE
Character counter not updated in IE8 and IE9

### ISSUE THREAD

**Issue by igomatjo** [mimo84/bootstrap-maxlength#106]
Hello!

Sorry, if this is a duplicated issue, but I couldn't find it.
When I enter some text in textbox or textarea and then delete some chars using backspace key then character counter is not updated in Internet Explorer 8 and 9 - character count doesn't decrease, but stays the same. If I re-select the textbox then it shows correct symbol count.
I'm using bootstrap-maxlength.js v 1.5.7

Thank you!

**Comment by mimo84** [comment]
Hi, I am sorry but this plugin doesn't support IE8 or 9.
To get old IE support you should use versions prior to 1.6 only.
Thanks.
