### ISSUE TITLE
allowOverMax

### ISSUE THREAD

**Issue by Petesta** [mimo84/bootstrap-maxlength#108]
You have listed the option `allowOverMax` in your examples to allow a user to go over the max length set by the textarea. However it is not listed in the Configurable Options section of the `README.md` and it's not in your source code. Does this functionality exist?

**Comment by mimo84** [comment]
Thank you for your fix. Yes this functionality was in the plugin however must have been removed by accident - my bad: there is no unit test to check the existance of this functionality.
