### ISSUE TITLE
no dist directory ?

### ISSUE THREAD

**Issue by michaelnguyen547** [mimo84/bootstrap-maxlength#115]
I install your plugin using bower. There is not dist directory as your commit said and there is no minified js file. Am I missing something ?

![2016-02-09_1232](https://cloud.githubusercontent.com/assets/436950/12928173/3777bf3e-cf29-11e5-8d79-af2873ff0eb3.png)

**Comment by E-VANCE** [comment]
+1 -- `bower install bootstrap-maxlength` didn't work for me, suspecting the missing dist-folder to be the culprit...

**Comment by djibe** [comment]
Please close issue.
Bower support is dropped.
Use git clone for now.
Npm is not updated yet.

**Comment by mimo84** [comment]
npm updated
