### ISSUE TITLE
 Get top value error second focus,

### ISSUE THREAD

**Issue by docikaci** [mimo84/bootstrap-maxlength#116]
![image](https://cloud.githubusercontent.com/assets/7788102/13868242/a57e44da-ed01-11e5-9c85-84f384f94130.png)
![image](https://cloud.githubusercontent.com/assets/7788102/13868232/97177e52-ed01-11e5-918b-23be0d2e8940.png)

chrome  49.0.2623.87

How to solve？ thanks

**Comment by auslee** [comment]
![image](https://cloud.githubusercontent.com/assets/7788102/13868280/eff33110-ed01-11e5-8f68-a5170d6f94fd.png)

**Comment by auslee** [comment]
right also，Offset down a little

**Comment by hallaathrad** [comment]
Your issue's description is not clear. I count the shown number of characters on each input field...
Is the issue related to the fact that the indicator is shown above the input field on your first image, but over the border and into the field on the other images? Please describe how you get this behaviour so we can replicate and help you solve it?
