### ISSUE TITLE
issuses on modal hide

### ISSUE THREAD

**Issue by Pinki18** [mimo84/bootstrap-maxlength#117]
Hello.
span with info doesn't hide when i close modal. Is it stil visible.
![przechwytywanie](https://cloud.githubusercontent.com/assets/1463487/13907764/0e45bd90-eef6-11e5-85c9-1cdfa4d0475c.PNG)

**Comment by roromix** [comment]
You can solve this issue with the option "appendToParent: true"

**Comment by adeoy** [comment]
It also worked for changing Tabs, thx :+1:
