### ISSUE TITLE
Add support for ContentEditable DIV

### ISSUE THREAD

**Issue by TheKillerremijn** [mimo84/bootstrap-maxlength#119]
Currently, a div with the contenteditable attribute is not supported, and will not update the counter

**Comment by hallaathrad** [comment]
@TheKillerremijn Have you been able to even show the counter on one of these? I can't.

**Comment by mimo84** [comment]
content editable is not supported. 
The editor you use for it should have support for it. This plugin is meant to be used only on inputs and textareas.
