### ISSUE TITLE
Localization impossible due to concatenated strings

### ISSUE THREAD

**Issue by c-schmitz** [mimo84/bootstrap-maxlength#121]
The localization of the input string is done by the following options

```
      separator: ' of ',
      preText: 'You have ',
      postText: ' chars remaining.',
```

In many languages this cannot be correctly translated because the sentences are composed in a different way/order than in English.

Instead an additional option should be introduced where you can give a whole sentence and use the JS equivalent of "printf" to format the replacement.

For example

hintText: "You have %1 of %2 chars remaining"

Since the placeholders represent the positions of the numbers they can be modified for any translation to be in the right place. Any other form or replacement tags would be fine, too.

Thank you for reading!

**Comment by c-schmitz** [comment]
I see this can be provided with the 'message' property - so it looks like it is a documentationt issue because I can't find this option on the manual page?

**Comment by mimo84** [comment]
Documentation is now containing the `message` option that allows for i18n.
