### ISSUE TITLE
Text area drag issue with badge position

### ISSUE THREAD

**Issue by sivajisanapala** [mimo84/bootstrap-maxlength#128]
![screenshot from 2016-10-06 18 35 54](https://cloud.githubusercontent.com/assets/20138121/19153720/45ce4470-8bf5-11e6-860c-d9533854fe02.png)

While dragging the text area for few times the feedback badge is getting fixed at some position.

**Comment by Zatsukai** [comment]
Bump. having the same issue. except the badge is always fixed whenever i scroll

**Comment by Zatsukai** [comment]
For anyone still looking for a solution to this, what worked for me was to change the maxlength option "appendToParent" to "true" as shown below. The plugin appends the indicator to the body by the fault and setting this option to true appends it to the input or the textarea instead.

![image](https://cloud.githubusercontent.com/assets/25033567/21848848/db1d7416-d7d0-11e6-9af7-5f5c7aa91dc0.png)

**Comment by mimo84** [comment]
Thank you @Zatsukai
