### ISSUE TITLE
zIndex problem

### ISSUE THREAD

**Issue by atsirigotis** [mimo84/bootstrap-maxlength#129]
I am using bootstrap v3.3.7 and modal zIndex is 10050. Currently the zIndex in bootstrap-maxlength is 1099. Could you please change it to 10100?

**Comment by lingceng** [comment]
I have an another z-index problem.
The indicator will still be shown when covered by a modal pop with `alwaysShow: true` option.

![image](https://user-images.githubusercontent.com/2259878/30791189-706c55a4-a176-11e7-96d1-a8f7c847bb8f.png)

It's not a good idea to just change z-index to some value. Maybe make it configurable?

**Comment by mimo84** [comment]
I think the fastest fix for this would be to temporarily change the z-index in the source code itself. (Line 441). I am planning to do a newer release with a configurable z-index, however at the moment I don't have time for it.

**Comment by ASKemp** [comment]
#141 
Added optional zIndex parameter in pull request

**Comment by djibe** [comment]
Please close issue,
fixed in 1.9.0.
