### ISSUE TITLE
Modal + Scroll, the counter is not positioned correctly

### ISSUE THREAD

**Issue by geodeveloper** [mimo84/bootstrap-maxlength#131]
If the plugin is used inside of bootstrap modal and the content of the body is scrollable, the counter is not positioned correctly.

1. Open the modal
2. Click on textarea (the counter appears)
3. Scroll down

I've a created a jsfiddle so you can reproduce the bug: https://jsfiddle.net/fbj14nd0/

Thank you.

**Comment by mimo84** [comment]
You can use the option `appendToParent: true` which has been designed for these scenarios.
Here is an updated fiddle: https://jsfiddle.net/fbj14nd0/1/

**Comment by geodeveloper** [comment]
Hi, thanks for your reply and solution. Didn't know the use of appendToParent. Have a great day!
