### ISSUE TITLE
Bootstrap 4 demo

### ISSUE THREAD

**Issue by djibe** [mimo84/bootstrap-maxlength#138]
Hi guys,
I created a fiddle for a working demo with Bootstrap 4 and Material Design (Daemonite kit from Github).
See it in action here : https://jsfiddle.net/djibe89/knv43w6t/
Enjoy ;-)

**Comment by nemchik** [comment]
Just an FYI to anyone who doesn't want to go to that extent, bootstrap4 works fine if you add the new badge classes:

```js
$("textarea").maxlength({
    limitReachedClass: "badge badge-danger",
    warningClass: "badge badge-success"
});
```

Although the demo posted by @djibe is very beautiful!

**Comment by djibe** [comment]
$("textarea").maxlength({
    alwaysShow: true,
    warningClass: "form-text text-muted mt-1",
    limitReachedClass: "form-text text-muted mt-1",
    placement: 'bottom-right-inside',
});

Is not much longer ;-)

**Comment by nemchik** [comment]
True, the bulk of it is comments (well documented, thank you!). What I meant was rather than using the whole material theme (which is beautiful) the existing look/functionality could be attained with BS4 just by using the badge classes. Should have clarified that in my post 😄
