### ISSUE TITLE
AllowOverMax not working

### ISSUE THREAD

**Issue by StephanBis** [mimo84/bootstrap-maxlength#140]
We're trying to dynamically add a maxlength to our form input who have the [data-val-maxlength-max] property on them. See below code how we managed to get it working. AllowOverMax does not let us go over the maximum amount of characters, is this option still supported in the latest version?

We also tried using the "customMaxAttribute" option, but this results in "NaN / data-val-maxlength-max" in the maxlength label. Tried the following: "data-val-maxlength-max", "val-maxlength-max" and also adding the attribute "custom-maxlength" instead of "maxlength" does not work.

So two seperate questions, but they do correspond to eachother.

```
$("input[data-val-maxlength-max], textarea[data-val-maxlength-max]").each(function (index, element) {
    $(element).attr("maxlength", $(element).data("val-maxlength-max"));
    $(element).maxlength({
        alwaysShow: true,
	allowOverMax: true,
	placement: "centered-right"
    });
});
```

**Comment by rafaeldruiz** [comment]
CustomMaxAttribute must be a string to work (customMaxAttribute: maxlength + '').

Set validate to false to allow over max (validate: false).

These changes worked for me.
