### ISSUE TITLE
Upgrade to last version

### ISSUE THREAD

**Issue by garbinmarcelo** [mimo84/bootstrap-maxlength#142]
Hi @mimo84, first thank you for this package, it is very useful.

Question:
Upgrading via yarn or npm is getting version 1.6, but the latest version is 1.7 as changelog.

How to upgrade from 1.6 to 1.7 (last version)?

**Comment by mimo84** [comment]
Hi, I have just managed to update the published npm package so now you can simply do:
`npm install bootstrap-maxlength --save`
