### ISSUE TITLE
Update NPM please

### ISSUE THREAD

**Issue by HamedFathi** [mimo84/bootstrap-maxlength#145]
Please update NPM package. 

**1.6.0 • Published 5 years ago**

[bootstrap-maxlength](https://www.npmjs.com/package/bootstrap-maxlength)

**Comment by virtualmix** [comment]
I support this suggestion. It would be great to be able to install and update the package with NPM.
Thank you for making this plugin.

**Comment by mimo84** [comment]
Hi, I managed to get back my access to npm and I fixed it. Just published version 1.10
