### ISSUE TITLE
yarn and max version 1.6.0

### ISSUE THREAD

**Issue by zak-wojtek77** [mimo84/bootstrap-maxlength#149]
Hello, when I try install by yarn I cannot install more version than 1.6.0.

yarn add bootstrap-maxlength@^1.7.0  # does not work

**Comment by djibe** [comment]
Unfortunately, mimo doesn't publish to NPM or Yarn any more.
You can integrate the files manually.

**Comment by zak-wojtek77** [comment]
Thank you for answer.

**Comment by mimo84** [comment]
It should work now as I have been able to get back npm access.

**Comment by zak-wojtek77** [comment]
thank you so much, now it works
