### ISSUE TITLE
How can I set current typed characters manually?

### ISSUE THREAD

**Issue by qwe0001** [mimo84/bootstrap-maxlength#153]
### DEMO

https://jsfiddle.net/0tx58ma1/6/

### What is the problem?

This plugin counts the number of characters currently typed in real time.

If you are typing with a keyboard, it will count the number of characters as you expect.

However, if you substitute a string with a click event using jQuery, it will not count the number of characters because it is not typing.

I would like the current character count to appear in the character counters when the button is clicked.

### What I want?

I wanna set current typed characters when I push button. How can I ???

**Comment by mimo84** [comment]
You can simply trigger an event after setting the characters, in your example you can change this line:

```
    $("#test").val("ypaaaa")
```
to

```
    $("#test").val("ypaaaa").trigger('input')
```
