### ISSUE TITLE
input returning as NaN

### ISSUE THREAD

**Issue by brianputz** [mimo84/bootstrap-maxlength#33]
Hello, I am having an issue where the input is continuously returning "NaN" I have been diving into the source and trying to debug what is actually happening and I am stuck. Here is the setup I have in my main script:

```
    $('textarea#charCount').maxlength({
        alwaysShow: true,
        threshold: 140,
        warningClass: "label label-info",
        limitReachedClass: "label label-warning",
        placement: 'bottom-right',
        preText: 'used ',
        separator: ' of ',
        postText: ' chars.'
    });
```

**Comment by jimbowatusi** [comment]
I didn't see where the `maxlength` was required either. For a quick fix if you have a consistent class defined, define the length with jQuery first.

            $('.char1000').attr('maxlength', 1000)
            $('.char1000').maxlength({
               alwaysShow: true,
               threshold: 1000,
               warningClass: 'label label-info',
               limitReachedClass: 'label label-danger',
               separator: ' characters out of ',
               validate: true
            });

**Comment by adsl99801** [comment]
[maxlength]="toNumber(myNum)" NaN will be 0
