### ISSUE TITLE
Issue when apply this plugin in a dialog with "position:fixed" and then user scrolls the page.

### ISSUE THREAD

**Issue by realdah** [mimo84/bootstrap-maxlength#46]
In my case, I am using bootstrap modal dialog for example, if I have a long page, even with a modal dialog opening, I can still scroll the page body behind.

Then, we will see the character indicator is scrolling along with page body because it is using "position:absolute" for positioning. please see screen shot below.

![snip20140211_1](https://f.cloud.github.com/assets/1226199/2137329/eb80580e-9323-11e3-95e9-a8963dac961a.png)

To solve this issue, I did two things together, one thing is the issue #45 which I raised for self protection.

Then, based on #45 , I changed my outside code to listen to the scroll event, when first scroll event happening, I saved the current focused element and call his "blur" event to destroy the label, then, after scroll complete, I called the element with "focus" event to recreate the label, then the new label will take the right position for sure.

However, since in #45 with isolated context, you choose to reuse existing label which means the label's position will not change, thus, that solution can't be used along with this issue.

Anyway, a proposed solution might be:
1) better plugin internally listen to scroll event, when scroll event starts, hide/destroy the label
2) when scroll events complete, re-calculate the position and then show/new the label.

Similar code like below

```
    function HandlingScrolledEvent() {
         // show/new the label
    }

    var timerHandle;
    function throttlingScrollEvents() {
        if(timerHandle) {
            window.clearTimeout(timerHandle);
            timerHandle = null;
        }

       // hide/destroy existing label
        timerHandle = window.setTimeout(HandlingScrolledEvent, 500);
    }

    //listen to global scroll event
    $(window).scroll(throttlingScrollEvents);
```

**Comment by esemlabel** [comment]
It doesnt work when parent element is <span>. It only works when parent element is <div>.

**Comment by kylerbeetun** [comment]
@esemlabel it works if the parent element is a <span>. See this updated fiddle of @mimo84  -> http://jsfiddle.net/Yg76w/8/ .
