### ISSUE TITLE
Obtain currentInput length

### ISSUE THREAD

**Issue by jefflam** [mimo84/bootstrap-maxlength#75]
Thanks for the nifty plugin!

I was wondering if there is any way I can obtain the length of the currentInput or 'character count left' value from the onSafeCount() or onOverCount() functions?

Right now, when the counter is over the limit it displays a negative value. I would want to obtain the value and display it as a positive with a changed message, such as: '5 characters over the limit' rather than '-5 characters left'.

Thanks in advance!

**Comment by BtM909** [comment]
Sorry to *re-open* but are you asking for us (the people) to add this to your (core) code or is do you have the ability to add plugins to maxlength?
