### ISSUE TITLE
MinLenght

### ISSUE THREAD

**Issue by lpalomo** [mimo84/bootstrap-maxlength#82]
Hi, I was wondering if you are open to adding a "minLenght" warning to the plugin (I think it doesn't support this already). Just a warning, no validation; for example, if the input length is less than N then show the widget label in red or yellow, and if the input length is longer or equal than N then show the widget label in green.

**Comment by BtM909** [comment]
I've actually added a warning treshold you can specifiy. This allows you to have 3 states (OK, Warning and Threshold). I assume it's very easy to add for @mimo84, otherwise I can do a pull request.

**Comment by mimo84** [comment]
If you have something for this please do open a PR, also please make sure to add some tests around the functionality.

**Comment by danieliancu** [comment]
+1
I find it really useful.

@BtM909 Are you still up with the PR?

**Comment by diego3** [comment]
+1 It is really very usefull

**Comment by BtM909** [comment]
I completely missed this... I'll craft up some PR (probably this weekend)

**Comment by hallaathrad** [comment]
How'd it go @BtM909? I'm working on this feature for I need it at work... wanna pair up for the PR?

**Comment by BtM909** [comment]
I have changed it locally, but haven't able to find time to create a PR (which I assume, should include some (unit-)testing.

**Comment by BtM909** [comment]
@hallaathrad, we can definitly work together for this PR. ping me an email @gmail.com.

**Comment by hallaathrad** [comment]
*knock knock*

**Comment by johnabela** [comment]
_whos there_

**Comment by BtM909** [comment]
@hallaathrad was a bit busy. Let's see if he has some more time right now?

**Comment by mimo84** [comment]
This issue has been inactive for a while. If you want to work on it and open a PR feel free to do so!
