### ISSUE TITLE
Add options to the docs

### ISSUE THREAD

**Issue by VladShcherbin** [mimo84/bootstrap-maxlength#89]
Consider adding all options to the docs, I wanted the element to be placed according to the parent element & even wrote my own plugin to do this because the default position did not count margin.
Then, I wanted to wrap this to plugin and send to bower, watched your src file and saw there **appendToParent** option. >:[

Please, update the docs with all the options, they might be critical to someone like me. Thanks

**Comment by mimo84** [comment]
Hi, thanks for noticing this. 
I updated the docs accordingly.
