### ISSUE TITLE
Reload after dynamic added field.

### ISSUE THREAD

**Issue by petericebear** [mimo84/bootstrap-maxlength#94]
Hello There,

I use knokcoutJS in a repeater field for field creations. When A new field is added i give another call with:
$('input[maxlength],textarea[maxlength]').maxlength({
 alwaysShow: true
});

Only the new dynamic fields don't get the maxlength boxes. Is there a function or another way to refresh?

**Comment by mimo84** [comment]
I think you should ask this question on Stackoverflow more than in here. Please post a link in this issue, since it might help someone else as well.

**Comment by petericebear** [comment]
This is the link:
http://stackoverflow.com/questions/28925092/bootstrap-maxlength-plugin

I do call the function, and I think it happens to all dynamic loaded fields. Static fields is no problem, but after the dom is loaded, and the function is called on the specific ID nothing happens for it.
